### ISSUE TITLE
탐색기 실행 시 폴더 경로의 글자가 깨져보임.

### ISSUE THREAD

**Issue by 4000king** [toolscode/findinfiles#6]
탐색기에서 폴더를 선택 후 실행 시 폴더명 글자가 깨져보이는 폴더가 있습니다.
그 폴더에서는 검색이 안되네요.

**Comment by toolscode** [comment]
불편을 드려 죄송합니다.

아래 정보를 주시면 분석에 도움이 될것 같습니다.
- Windows 버전
- FindInFiles 버전
- FindInFiles 에러화면 캡쳐

확인부탁드립니다.

**Comment by 4000king** [comment]
OS : Windows 10 Pro

APP : 3.5.7.1

 

작은 요청사항… ^^

 

1. App 을 실행시켰을 때 버전을 볼 수 있으면 좋겠습니다.

지금은 프로그램 삭제까지 들어가야 볼 수 있으니 불편.

 

2. App 화면의 “찾을 문자”, “찾을 파일” 입력부의 폰트 크기가 좀더 컸으면…. ^^

나이 먹은 사람일수록 글자 크기가 좀더 큰 걸 좋아합니다.

**Comment by toolscode** [comment]
프로그램 버전은 About창을 보시면 있습니다.

<img width="688" alt="Screen Shot 2019-12-14 at 14 37 36" src="https://user-images.githubusercontent.com/46835624/70844100-7cb2e480-1e7f-11ea-9fda-58c62ee05a11.png">

폰트의 크기는 고려해보도록 하겠습니다.

의견 감사합니다.

**Comment by 4000king** [comment]
아…. 설정과 about 이 좌상단 아이콘을 클릭했을 때 나올줄은 몰랐네요…

**Comment by toolscode** [comment]
FindInFiles v3.5.8 build 270에서 수정되었습니다.
확인해보시고 문제가 있으시면 다시 issue 남겨주세요.

감사합니다.

**Comment by toolscode** [comment]
설치 하시고 반드시 Windows 부팅을 해야 새로운 모듈이 동작합니다.

참고하세요.

**Comment by 4000king** [comment]
네 알겠습니다
감사합니다. 평소에 잘 쓰고 있습니다.



2019년 12월 14일 (토) 오후 9:26, toolscode <notifications@github.com>님이 작성:

**Comment by toolscode** [comment]
FindInFiles v3.5.8 build 270에 적용 완료
